### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by cyanide747** [Klixxx/ElvUI_KlixUI#1]
The below two messages are causing me to not be able to turn in a quest.
Message: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: QuestFrame:SetPoint.
Time: Mon Aug 12 20:21:28 2019
Count: 1
Stack: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: QuestFrame:SetPoint.
[C]: ?
[C]: ?
[C]: in function `SetPoint'
Interface\FrameXML\UIParent.lua:2751: in function `UpdateUIPanelPositions'
Interface\FrameXML\UIParent.lua:2372: in function <Interface\FrameXML\UIParent.lua:2361>
[C]: in function `SetAttribute'
Interface\FrameXML\UIParent.lua:3451: in function <Interface\FrameXML\UIParent.lua:3449>
[C]: in function `securecall'
Interface\FrameXML\UIParent.lua:2648: in function `SetUIPanel'
Interface\FrameXML\UIParent.lua:2552: in function `ShowUIPanel'
Interface\FrameXML\UIParent.lua:2365: in function <Interface\FrameXML\UIParent.lua:2361>
[C]: in function `SetAttribute'
Interface\FrameXML\UIParent.lua:3212: in function `ShowUIPanel'
Interface\FrameXML\QuestFrame.lua:97: in function <Interface\FrameXML\QuestFrame.lua:20>

Message: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: QuestFrame:SetPoint.
Time: Mon Aug 12 20:22:11 2019
Count: 2
Stack: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: QuestFrame:SetPoint.
[C]: ?
[C]: ?
[C]: in function `SetPoint'
...ce\AddOns\ElvUI_KlixUI\modules\blizzard\blizzard.lua:186: in function <...ce\AddOns\ElvUI_KlixUI\modules\blizzard\blizzard.lua:177>
[C]: ?
[C]: in function `Show'
Interface\FrameXML\UIParent.lua:2652: in function `SetUIPanel'
Interface\FrameXML\UIParent.lua:2552: in function `ShowUIPanel'
Interface\FrameXML\UIParent.lua:2365: in function <Interface\FrameXML\UIParent.lua:2361>
[C]: in function `SetAttribute'
Interface\FrameXML\UIParent.lua:3212: in function `ShowUIPanel'
Interface\FrameXML\QuestFrame.lua:97: in function <Interface\FrameXML\QuestFrame.lua:20>

Locals:

**Comment by cyanide747** [comment]
* this issue seems to go away when disabling questguru 8.2.0 which is the latest version of this mod.

**Comment by Klixxx** [comment]
I've found the issues, was an easy fix, it should work now, ill push an update soon!

Thanks for reporting!

**Comment by Klixxx** [comment]
Fixed
