### ISSUE TITLE
achivement

### ISSUE THREAD

**Issue by cyanide747** [Klixxx/ElvUI_KlixUI#2]
I get the following when accessing my achievements, it persists popping up every time my mouse cursor is centered. have to reload ui to get it to go away

Message: ...ns\Blizzard_AchievementUI\Blizzard_AchievementUI.lua:727: Usage: GetCategoryNumAchievements(categoryID, includeSuperceded)
Time: Sat Aug 17 22:25:41 2019
Count: 4
Stack: ...ns\Blizzard_AchievementUI\Blizzard_AchievementUI.lua:727: Usage: GetCategoryNumAchievements(categoryID, includeSuperceded)
[C]: ?
[C]: in function `GetCategoryNumAchievements'
...ns\Blizzard_AchievementUI\Blizzard_AchievementUI.lua:727: in function `AchievementFrameComparison_UpdateStatusBars'
...ns\Blizzard_AchievementUI\Blizzard_AchievementUI.lua:2938: in function <...ns\Blizzard_AchievementUI\Blizzard_AchievementUI.lua:2935>

Locals:

**Comment by Klixxx** [comment]
What version are you on?
I have fixed this, maybe it was on my dev. version i fixed it, please download version 1.62 and test again!

Thanks

**Comment by Klixxx** [comment]
This is fixed
