### ISSUE TITLE
Elvui won't load after 1.62 update

### ISSUE THREAD

**Issue by Michri64** [Klixxx/ElvUI_KlixUI#3]
Just started up the machinery this morning and updated S&L and klixUI through the twitch app. Immediately realized i'm now missing the infobars under the chat window, the one in the bottom middle of the screen normally showing my stats, and the one down in the right corner showing my fps and latency.

Thinking i'd have to do the install again, i noticed that KlixUI isn't being loaded and i can't even see it when i press esc to get the game menu shown. I downgraded to 1.61 and the problem isn't showing with that - below is the error i get when running 1.62 just after logging in.

Message: Interface\AddOns\ElvUI_KlixUI\core\core.lua:156: attempt to call method 'HookInitialize' (a nil value)
Time: Sun Aug 18 10:53:18 2019
Count: 1
Stack: Interface\AddOns\ElvUI_KlixUI\core\core.lua:156: attempt to call method 'HookInitialize' (a nil value)
Interface\AddOns\ElvUI_KlixUI\core\core.lua:156: in main chunk

Locals: E = <table> {
 GetTimeInfo = <function> defined @Interface\AddOns\ElvUI\Core\Math.lua:314
 mylevel = 120
 Bags = <table> {
 }
 resolution = "1920x1080"
 HandleCommandBar = <function> defined @Interface\AddOns\ElvUI\Core\API.lua:120
 CancelTimer = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua:147
 FormatMoney = <function> defined @Interface\AddOns\ElvUI\Core\Math.lua:368
 ExitVehicleShowFrames = <function> defined @Interface\AddOns\ElvUI\Core\API.lua:410
 HelloKittyToggle = <function> defined @Interface\AddOns\ElvUI\Core\AprilFools.lua:353
 UpdateUnitFrames = <function> defined @Interface\AddOns\ElvUI\Core\Core.lua:867
 CopyTable = <function> defined @Interface\AddOns\ElvUI\Core\Core.lua:510
 DispelClasses = <table> {
 }
 SetMoversPositions = <function> defined @Interface\AddOns\ElvUI\Core\Movers.lua:480
 ScheduleTimer = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua:94
 PriestColors = <table> {
 }
 UpdateDB = <function> defined @Interface\AddOns\ElvUI\Core\Core.lua:834
 SetupTheme = <function> defined @Interface\AddOns\ElvUI\Core\Install.lua:166
 media = <table> {
 }
 UnlocalizedClassName = <function> defined @Interface\AddOns\ElvUI\Core\API.lua:46
 EnableBlizzardAddOns = <function> defined @Interface\AddOns\ElvUI\Core\Commands.lua:215
 UIScale = <function> defined @Interface\AddOns\ElvUI\Core\PixelPerfect.lua:27
 db = <table> {
 }
 FramesOverlap = <function> defined @Interface\AddOns\ElvUI\Core\Math.lua:111
 SetEnabledState = <function> defined @Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceHook-3.0\AceHook-3.0.lua:274
 Options = <table> {
 }
 UpdateLayout = <function> defined @Interface\AddOns\ElvUI\Core\Core.lua:885
 Layout = <table> {
 }
 PluginInstaller = <table> {
 }
 PixelBestSize = <function> defined @Interface\AddOns\ElvUI\Core\PixelPerfect.lua:69
 UnregisterEventForObject = <function> defined @Interface\AddOns\ElvUI\Core\Core.lua:1147
 Distributor = <table> {
 }
 HiddenFrame = <unnamed> {
 }
 Media = <table> {
 }
 PositionGameMenuButton = <function> defined @Interface\AddOns\ElvUI\init.lua:217
 ScanTooltipTextures = <function> defined @Interface\AddOns\ElvUI\init.lua:115
 SafeGetPoint = <function> defined @Interface\AddOns\ElvUI\Core\Toolkit.lua:20
 UIFrameFade = <function> defined @Interface\AddOns\ElvUI\Core\Animation.lua:212
 MinimapWidth = 150
 StaticPopup_IsLastDisplayedFrame = <function> defined @Interface\AddOns\ElvUI\Core\StaticPopups.lua:588
 StaticPopup_CreateSecureButton = <function> defined @Interface\AddOns\ElvUI\Core\StaticPopups.lua:1150
 Truncate = <function> defined @Interface\AddOns\ElvUI\Core\Math.lua:92
 UpdateBackdropColors = <function> defined @Interface\AddOns\ElvUI\Core\Core.lua:439
 TimeThreshold = 3
 ToggleMoveMode = <function> defined @Interface\AddOns\ElvUI\Core\Config.lua:58
 RemoveTableDuplicates = <function> defined @Interface\AddOns\ElvUI\Core\Core.lua:547
 name = "ElvUI"
 WorldMap = <table> {
 }
 MinimapHeight = 150
 Disable = <function> defined @Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:314
 DF = <table> {
 }
 SlideOut = <function> defined @Interface\AddOns\ElvUI\Core\Animation.lua:147
 isMacClient = false
 Print = <function> defined @Interface\AddOns\ElvUI\Core\Core.lua:194
 Install = <function> defined @Interface\AddOns\ElvUI\Core\Install.lua:719
 UnregisterObjectForVehicleLock = <function> defined @Interface\AddOns\ElvUI\Core\API.lua:381
 LockedCVars = <table> {
 }
 TogglePixelBorders = <function> defined @Interface\AddOns\ElvUI\Core\Toolkit.lua:96
 TimeFormats = <table>

**Comment by Klixxx** [comment]
Did you download latets ElvUI version? 11.21? cause it wont load without the newest ElvUI version installed

**Comment by Michri64** [comment]
Sorry, i missed that Elvui needed an update as well. Sadly didn't help on the problem. two lua error show ups when updated to newest elvui, klixui and S&L: 
Message: ...\AddOns\ElvUI_KlixUI\modules\maps\minimapbuttons.lua:400: attempt to index field 'db' (a nil value)
Time: Sun Aug 18 11:51:52 2019
Count: 1
Stack: ...\AddOns\ElvUI_KlixUI\modules\maps\minimapbuttons.lua:400: attempt to index field 'db' (a nil value)
[C]: ?
...\AddOns\ElvUI_KlixUI\modules\maps\minimapbuttons.lua:400: in function `Initialize'
Interface\AddOns\ElvUI_KlixUI\core\core.lua:55: in function `InitializeModules'
Interface\AddOns\ElvUI_KlixUI\core\core.lua:115: in function `?'
...\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:313: in function <...\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:309>
[C]: in function `Initialize'
Interface\AddOns\ElvUI\init.lua:205: in function <Interface\AddOns\ElvUI\init.lua:204>

Locals: 

**and** 

Message: ...nterface\AddOns\ElvUI_KlixUI\modules\skins\skins.lua:1014: attempt to index field 'SLE_RaidMarkerBar' (a nil value)
Time: Sun Aug 18 11:51:54 2019
Count: 1
Stack: ...nterface\AddOns\ElvUI_KlixUI\modules\skins\skins.lua:1014: attempt to index field 'SLE_RaidMarkerBar' (a nil value)
(tail call): ?
...nterface\AddOns\ElvUI_KlixUI\modules\skins\skins.lua:1014: in function <...nterface\AddOns\ElvUI_KlixUI\modules\skins\skins.lua:990>
...nterface\AddOns\ElvUI_KlixUI\modules\skins\skins.lua:1137: in function `?'
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...s\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...s\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by Michri64** [comment]
I've reinstalled elvui, updated the client and rebooted my computer, Klixui still won't show

**Comment by Klixxx** [comment]
Please type /kuierror on
and see if the error is still there

**Comment by Michri64** [comment]
Nothing happens when typing that, other than /help for commands. I disabled some of the addons and found that ProjectAzilroka was the problem. 

Sorry for the inconvenience. 

Thanks for a great ui
