### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by cyanide747** [Klixxx/ElvUI_KlixUI#4]
downloaded latest elvui and klixui today and upon logging in I get this persistant LUA error I had to screen shot the below and type it because the error was just counting up rapidly. I did /Klixuierror on which disabled all addons but Klix and ElvUI but the problem persists. There is probably more to this message I just cant access the rest of it due to the repeated error

Message:
...ace\AddOns\ElvUI_KlixUI\modules\locpanel\tooltip.lua:27
7: attempt to call field 'C_Map_GetBestMapForUnit' (a nil value)
Time: Mon Aug 19 19:02:21 2019
Count: 547
Stack:
...ace\AddOns\ElvUI_KlixUI\modules\locpanel\tooltip.lua:27
7: attempt to call field 'C_Map_GetBestMapForUnit' (a nil value)
[C]: in fucntion 'C_Map_GetBestMapForUnit'
...ace\Addons\ElvUI_KlixUI\modules\locpanel\tooltip.lua:27
7 in function 'GetLevelRange'
...ce\Addons\ElvUI_KlixUI\modules\locpanel.lua:4
04: in function
<...ce\Addons\Elvui_Klixui\modules\locpanel\locpanel.lua:
341>

**Comment by cyanide747** [comment]
I just wanted to note that I did try deleting the file and a clean install with the same result.

**Comment by nazrion** [comment]
hiya, I wondered what was wrong.  But if you revert back to v1.61 I believe and it works.

**Comment by Klixxx** [comment]
The issue has been fixed in my development branch
I release a fixed version later today.

**Comment by Klixxx** [comment]
This is fixed in v1.64
