### ISSUE TITLE
issue with talents

### ISSUE THREAD

**Issue by nazrion** [Klixxx/ElvUI_KlixUI#5]
Message: ...face\AddOns\ElvUI_KlixUI\modules\talents\talents.lua:223: attempt to index field 'ishadow' (a nil value)
Time: Sat Aug 24 18:09:15 2019
Count: 1
Stack: ...face\AddOns\ElvUI_KlixUI\modules\talents\talents.lua:223: attempt to index field 'ishadow' (a nil value)
(tail call): ?
...face\AddOns\ElvUI_KlixUI\modules\talents\talents.lua:223: in function `InitSpecIcons'
...face\AddOns\ElvUI_KlixUI\modules\talents\talents.lua:276: in function `?'
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...ace\AddOns\TomTom\libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...ace\AddOns\TomTom\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

Tried resetting the profile and deleting cache.  And had to delete PA as well for some reason the UI does not load if that addon is loaded.. but I only used PA for the square mini-map and button bar which are part of KlixUI.  Its a nicer, all around UI than the other Elvui edits I've downloaded.

**Comment by Klixxx** [comment]
Fixed in v1.67
