### ISSUE TITLE
Please hurry

### ISSUE THREAD

**Issue by wicatfly** [Klixxx/ElvUI_KlixUI#6]
**Please help me to fix this:**

Message: ...rface\AddOns\ElvUI_KlixUI\modules\armory\options-设置选项.lua:311: attempt to index field 'itemLevelInfo' (a nil value)
Time: Tue Sep 10 23:24:55 2019
Count: 1
Stack: ...rface\AddOns\ElvUI_KlixUI\modules\armory\options-设置选项.lua:311: attempt to index field 'itemLevelInfo' (a nil value)
...\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:165: in function <...\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:159>
[C]: ?
Interface\AddOns\ElvUI\init.lua:315: in function <Interface\AddOns\ElvUI\init.lua:303>
[C]: in function `ToggleOptionsUI'
Interface\AddOns\ElvUI_KlixUI\core\gameMenu.lua:10: in function <Interface\AddOns\ElvUI_KlixUI\core\gameMenu.lua:10>

Locals: self = <unnamed> {
 0 = <userdata>
}
_ = "ADDON_LOADED"
addon = "ElvUI_OptionsUI"
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 ElvUI_LocationPlus = <table> {
 }
 LibElv-GameMenu-1.0 = <table> {
 }
 ElvUI_KlixUI = <table> {
 }
}
(for control) = "ElvUI_KlixUI"
_ = "ElvUI_KlixUI"
plugin = <table> {
 version = "0.05"
 callback = <function> defined @Interface\AddOns\ElvUI_KlixUI\core\core.lua:64
 name = "ElvUI_KlixUI"
}
lib = <table> {
 VCFrame = <unnamed> {
 }
 index = 0
 StripVersion = <function> defined @Interface\AddOns\ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:206
 SendMessageWaiting = true
 OptionsUILoaded = <function> defined @Interface\AddOns\ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:159
 groupSize = 0
 GenerateVersionCheckMessage = <function> defined @Interface\AddOns\ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:173
 prefix = "ElvUIPluginVC"
 plugins = <table> {
 }
 Initialized = <function> defined @Interface\AddOns\ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:308
 GetPluginOptions = <function> defined @Interface\AddOns\ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:183
 VersionCheck = <function> defined @Interface\AddOns\ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:212
 CFFrame = <unnamed> {
 }
 ClearSendMessageWait = <function> defined @Interface\AddOns\ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:265
 inits = <table> {
 }
 RegisterPlugin = <function> defined @Interface\AddOns\ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:104
 GeneratePluginList = <function> defined @Interface\AddOns\ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:248
 DelayedSendVersionCheck = <function> defined @Interface\AddOns\ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:149
 HookInitialize = <function> defined @Interface\AddOns\ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:318
 registeredPrefix = true
 SendPluginVersionCheck = <function> defined @Interface\AddOns\ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:269
}
pairs = <function> defined =[C]:-1

**Comment by Klixxx** [comment]
Fixed in v0.06 this is classic right?

**Comment by wicatfly** [comment]
> 
> 
> Fixed in v0.06 this is classic right?

Yes.I just try it,but there are new errors:

.s\ElvUI_KlixUI\modules\skins\blizzard\stacksplit.lua:8: attempt to index field 'backdrop' (a nil value)
Count: 1

Call Stack:
(tail call): ?
...s\ElvUI_KlixUI\modules\skins\blizzard\stacksplit.lua:8: in function <...s\ElvUI_KlixUI\modules\skins\blizzard\stacksplit.lua:4>
[C]: ?
ElvUI\Modules\skins\Skins.lua:1312: in function <ElvUI\Modules\skins\Skins.lua:1298>
[C]: ?
ElvUI\Core\Core.lua:1199: in function `CallLoadFunc'
ElvUI\Core\Core.lua:1214: in function `CallLoadedModule'
ElvUI\Core\Core.lua:1240: in function `InitializeModules'
ElvUI\Core\Core.lua:1450: in function <ElvUI\Core\Core.lua:1429>
[C]: in function `Initialize'
ElvUI\init.lua:220: in function <ElvUI\init.lua:219>

**Comment by Klixxx** [comment]
do you use another addon to handle the stack split in your bags?

**Comment by wicatfly** [comment]
> 
> 
> do you use another addon to handle the stack split in your bags?

no，I just use tdPack2 and Bagnon for bag, and I have tried to disable all addons except Evlui and KlixUI, not working

**Comment by wicatfly** [comment]
Also this :

Message: Interface\AddOns\ElvUI_KlixUI\modules\efl\efl.lua:127: attempt to call field 'GetFriendInfo' (a nil value)
Time: Wed Sep 11 11:13:43 2019
Count: 1
Stack: Interface\AddOns\ElvUI_KlixUI\modules\efl\efl.lua:127: attempt to call field 'GetFriendInfo' (a nil value)
[C]: in function `SetAttribute'
Interface\FrameXML\UIParent.lua:2526: in function `ShowUIPanel'
Interface\FrameXML\FriendsFrame.lua:1113: in function `ToggleFriendsFrame'
[string "TOGGLESOCIAL"]:1: in function <[string "TOGGLESOCIAL"]:1>

Locals: (*temporary) = <unnamed> {
 0 = <userdata>
 ShowUIPanel = <function> defined @Interface\FrameXML\UIParent.lua:1808
 UpdateUIPanelPositions = <function> defined @Interface\FrameXML\UIParent.lua:2156
 left = FriendsFrame {
 }
 HideUIPanel = <function> defined @Interface\FrameXML\UIParent.lua:2104
 ShowUIPanelFailed = <function> defined @Interface\FrameXML\UIParent.lua:2014
 MoveUIPanel = <function> defined @Interface\FrameXML\UIParent.lua:2084
 SetUIPanel = <function> defined @Interface\FrameXML\UIParent.lua:2020
 UIParentManageFramePositions = <function> defined @Interface\FrameXML\UIParent.lua:2267
 GetUIPanel = <function> defined @Interface\FrameXML\UIParent.lua:2148
}
(*temporary) = "panel-show"
(*temporary) = "panel-show"
(*temporary) = true
(*temporary) = <function> defined =[C]:-1

**Comment by Klixxx** [comment]
Can you please open up an issue ticket for the classic version and not the retail.

https://github.com/Klixxx/ElvUI_KlixUI-Classic/issues
